combine m12 and m13 json config files
q-pup/q-pup-design pull request #10
Opened 2022-02-17 06:14 UTC by dawsonhemphill

2022-02-17 22:49 UTC, wmmc88 requested changes
Found some differences by diffing. Also the formatting is different than the other jsons. could u go in vscode and click format?

2022-02-17 22:49 UTC, wmmc88 commented on odrive/torque_test/m12_13.json
> +            "pre_calibrated": false,
true on other axis

2022-02-17 22:49 UTC, wmmc88 commented on odrive/torque_test/m12_13.json
> +            "load_encoder_axis": 1,
```suggestion
            "load_encoder_axis": 0,
```

2022-02-20 00:18 UTC, matthew-reynolds commented on odrive/torque_test/m12_13.json
> +            "load_encoder_axis": 1,
resolved in 35299e41b48b630da2b45f66460a1852e762b9fc

2022-02-20 00:19 UTC, matthew-reynolds commented on odrive/torque_test/m12_13.json
> +            "pre_calibrated": false,
not resolved in 35299e41b48b630da2b45f66460a1852e762b9fc. dunno if we do or dont want enc precalibrated, but it should at least be consistent

@dawsonhemphill @wraftus

2022-02-20 00:19 UTC, wraftus commented
Retuned M13's controller and played with the `vel_limit` and `current_control_bandwidth`, notes in commit message.

I also renamed the combined file `m12_13` to `m13_m12` to reflect that m13 goes in M0, this naming convention should make things a little easier on our brains

2022-02-20 00:28 UTC, wraftus commented on odrive/torque_test/m12_13.json
> +            "pre_calibrated": false,
Should leave it as false I think, m12 hasn't actually been calibrated since it got reassembled iirc, so the encoder calib is likely wrong

2022-03-01 19:23 UTC, matthew-reynolds commented on odrive/torque_test/m12_13.json
> +            "pre_calibrated": false,
#11

2022-03-01 19:24 UTC, matthew-reynolds approved these changes

2022-03-01 19:24 UTC, merged